### ISSUE TITLE
Is this the Play-Store app?

### ISSUE THREAD

**Issue by szaimen** [ONLYOFFICE/documents-app-android#1]
Hey, I wonder if this is the Play-Store Onlyoffice app:
https://play.google.com/store/apps/details?id=com.onlyoffice.documents
Can you please confirm or reject?

**Comment by nav-fess** [comment]
Yes that's it

**Comment by szaimen** [comment]
Great! Could you maybe add a link from the readme to the playstore? 
Then it would be a bit better to discover that this is the play-store app :)

**Comment by szaimen** [comment]
Seems like already done. Thanks!
