### ISSUE TITLE
Possibility to disable dark mode

### ISSUE THREAD

**Issue by derritter88** [ONLYOFFICE/documents-app-android#158]
Hello there,

I am using Onlyoffice on Android as my primary PDF viewer.
Unfortunately after the last update it uses dark mode according to my Android setup in general without the possibility to disable it.

Therefore if I have a pdf document with a QR code on it the other QR reader is unable to read the code due to dark mode.

**Comment by nav-fess** [comment]
Hello.  Attach the file please.  When inverting color, you can follow the link QR -code

**Comment by derritter88** [comment]
Hello @nav-fess ,

please find attached a screenshot of my mobile phone - if you need to full pdf I can share it with you via email due to privacy concerns.

![Screenshot_20220126-213901_ONLYOFFICE_Dokumente](https://user-images.githubusercontent.com/8606313/151243422-e23fc959-c37e-4c0b-a2bd-0bea80f3a081.png)


> When inverting color, you can follow the link QR -code
But I would need to do this on system level and not on application level, right?

**Comment by nav-fess** [comment]
> Thank you. I can confirm - this is a bug, issue 42718 in our internal issue tracker

Уеs,  that right 

>please find attached a screenshot of my mobile phone - if you need to full pdf I can share it with you via email due to privacy concerns.

Added QR to pdf.   The bug did not reproduce . 
[QR.pdf](https://github.com/ONLYOFFICE/documents-app-android/files/7948660/QR.pdf)

Issue 55131 for switching app theme in our internal bug tracker

**Comment by michael-efremov** [comment]
Will be available in 5.4.0 #165

**Comment by michael-efremov** [comment]
Will be available in 5.4.0 #165
