### ISSUE TITLE
[Issue] Input behavior on Spreadsheet

### ISSUE THREAD

**Issue by MajinSaaY** [ONLYOFFICE/documents-app-android#175]
It's hard to type in any cell, specially if you have to edit, the cursor keeps moving back. Check the gif:
![InShot_20220302_083455866](https://user-images.githubusercontent.com/43237261/156355029-52b64708-99cb-4c9c-93ce-1d3a9dc152be.gif)

**Comment by nav-fess** [comment]
Hello, @MajinSaaY 
Thank you. I can confirm - this is a bug, issue 52599 in our internal issue tracker.
