### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by szaimen** [ONLYOFFICE/documents-app-android#2]
Hey, 
would be great if you could publish this app on F-Droid!
Thanks!

**Comment by TheOneWithTheBraid** [comment]
I think we would need an option to build without Play Services then. Currently, lots of Google and Facebook stuff is included: https://reports.exodus-privacy.eu.org/en/reports/com.onlyoffice.documents/latest/

Maybe someone could add a build flavour without them?

**Comment by linsui** [comment]
We need not only a flavor. Do you know how to build this app? See https://github.com/ONLYOFFICE/documents-app-android/blob/main/app_manager/settings.gradle Looks like there are lots of code from other repos is required. I do not find `core-ext` and `document-android-editors`. If they are not open source, we can build this app.

**Comment by meximan** [comment]
Any updates on this?

**Comment by linsui** [comment]
There won't be update. See https://github.com/ONLYOFFICE/documents-app-android/issues/32#issuecomment-831988663. This is not an FOSS app.

**Comment by user12w** [comment]
Please add your app to F-Droid.

**Comment by Andrew-Dudov** [comment]
It was not planned to publish our application in F-Droid

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
