### ISSUE TITLE
Using the keyboard, a space is inserted | Chromebook

### ISSUE THREAD

**Issue by JoFo-IT** [ONLYOFFICE/documents-app-android#209]
# OS
Chromebook
Version 101.0.4951.72 (Offizieller Build) (32-Bit)
Lenovo CT-X636F

# File Typ
Textdokument

# Problem
When entering text using the keyboard, a space is inserted between each letter. ("T h i s  i s  a  T e s t ")

![image](https://user-images.githubusercontent.com/72133036/172600018-bd299691-928e-494d-a69c-a3999f99e487.png)

**Comment by alexisju** [comment]
Another issue maybe linked : if i connect my smartphone (Android 14 + OO 7.5.1)) to an external monitor (usb c with SamsungDex) with a Bluetooth keyboard, every characters are inserted twice (hheelloo wwoorrlldd..). If i disconnect the monitor but keep writing with the external keyboard, it is ok. (Btw in this configuration with a BT mouse it is impossible to scroll with the mouse).

**Comment by Andrew-Dudov** [comment]
Hello @alexisju create another issue with your request

**Comment by Andrew-Dudov** [comment]
@JoFo-IT Is the bug relevant in the current version?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
