### ISSUE TITLE
Keyboard doesn't show up after using back gesture

### ISSUE THREAD

**Issue by ghost** [ONLYOFFICE/documents-app-android#231]
The keyboard doesn't appear after dismissing it with back gesture.
https://user-images.githubusercontent.com/79187956/185045323-31ef5447-89ac-480a-8375-dfeef20cfb0d.mp4

**Comment by Andrew-Dudov** [comment]
Hello, @unomi-zan, thanks for contacting. I confirm your problem,  so i created a new issue 58572 in our private issue tracker.

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed.
I close this issue. Feel free to comment or reopen it if you got further questions.
