### ISSUE TITLE
OnlyOffice folder and the sample documents are constantly recreated without user consent

### ISSUE THREAD

**Issue by Magneticdud** [ONLYOFFICE/documents-app-android#235]
The android app is recreating /OnlyOffice and the three sample documents even if the user deleted the folder.

Personally, I hate when Android apps create their own folder in storage, it totally doesn't need it.

Please allow choosing another folder as main, for example /Documents or /Downloads

Also, because the average user has no idea how to use a file browser, they just save everything in /Downloads and when they open the app they won't see the documents they just downloaded

**Comment by Magneticdud** [comment]
Thanks for your quick response, I meant to do like Microsoft Word, it shows documents and downloads first, maybe they got some special permission 

![Screenshot_20220906-143231](https://user-images.githubusercontent.com/2940598/188636122-22c04131-eb37-4fec-8bf8-c95296152c7d.png)

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
