### ISSUE TITLE
Spreadsheets - input block after usage of S Pen

### ISSUE THREAD

**Issue by AndyFx12** [ONLYOFFICE/documents-app-android#236]
After some usage of S Pen (Samsung Galaxy Tab S6 lite), it´s impossible to select/change a cell.
It occurs, if you lay down your hand on the display. So it seems, hand-detection of S-Pen stops input completely.

It´s possible to move arround the sheet - and it´s possible to save your document. 
But no input.

I´am using V5.4.0 on Samsung S6 lite with Android 12.

regards, Andy

**Comment by AndyFx12** [comment]
It sounds great! Is there any beta-version available?

**Comment by Andrew-Dudov** [comment]
@AndyFx12 We are preparing to release a new version. Wait updates in Google play

**Comment by Andrew-Dudov** [comment]
The bug is not reproducible on the latest version

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
