### ISSUE TITLE
Error upon tapping folder icon

### ISSUE THREAD

**Issue by iHnR** [ONLYOFFICE/documents-app-android#238]
When I tap the folder icon, I get the toast notification shown below. I did experience the same issue with [Obsidian](https://obsidian.md/), but other apps can access the file manager just fine.

![Screenshot_20220916-202110](https://user-images.githubusercontent.com/62661051/190708379-52c27876-a5bd-450d-a267-c02af614fa04.jpg)

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
