### ISSUE TITLE
Android App - can't connect Nextcloud with username containing @

### ISSUE THREAD

**Issue by roosei** [ONLYOFFICE/documents-app-android#244]
Hello,

in Android app 4.0.0 when using "Connect to Nextcloud" I'm unable to sign in with domain user, e.g. "user@domain.com" (because of LDAP auth). 

With "admin" user it works perfectly but not with the domain one - it returns "Address not found".

Also note we're using Nextcloud 2FA module.

Thank you!

**Comment by SergeyKorneyev** [comment]
@roosei 
The original issue should be resolved now: the app will use the authorization method provided by the Nextcloud portal.

@b90g 
If that does not provide a fix for your particular scenario, please create a separate issue so we could take a look at it.
