### ISSUE TITLE
can not build in android debug mode.....how to fix it...??

### ISSUE THREAD

**Issue by amirshehzadcdz** [ONLYOFFICE/documents-app-android#251]
Could not determine the dependencies of task ':appmanager:compileManagerDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':appmanager:managerDebugCompileClasspath'.
   > Could not resolve project :libx2t.
     Required by:
         project :appmanager
      > No matching configuration of project :libx2t was found. The consumer was configured to find an API of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.ProductFlavor:version' with value 'manager', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.3.0', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.
   > Could not resolve project :libeditors.
     Required by:
         project :appmanager
      > No matching configuration of project :libeditors was found. The consumer was configured to find an API of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.ProductFlavor:version' with value 'manager', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.3.0', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'

**Comment by Andrew-Dudov** [comment]
Hello @amirshehzadcdz. The question is considered in the issue https://github.com/ONLYOFFICE/documents-app-android/issues/32,
 I recommend that you read it.

**Comment by amirshehzadcdz** [comment]
okay thanks
