### ISSUE TITLE
Writer, deleting a character deletes multiple ones or concatinates words + every character in a new space

### ISSUE THREAD

**Issue by sharpclone** [ONLYOFFICE/documents-app-android#253]
**Steps to reproduce:**
1. Open any writer document 
2. Start typing 
3. Try to delete some characters...

**Expected Behavior**
Type normally and remove the characters normally 

**Actual Behavior** 
It removes multiple characters or even concatenates the current word with the one before when i try to delete..It's even worse sometimes, every character is written in a new space like this: T E X T

**Video(important)**: 
1.[Here(nextcloud)](https://rockpuff.ddns.net/index.php/s/LJp3maLryoG3y95) 
2.(trying with another keyboard app)[Here](https://rockpuff.ddns.net/index.php/s/LCPsiaX9n7k6Fao)

**Software info:**
AppInfo: Ver. 5.5.2 , Build 410, SDK 7.2.2.19
PhoneModel: JNY-LX1
OS : android 10
Kernel: 4.14.116
Keyboard Apps: AnySoftKeyboard,  Simple Keyboard
Languages used in keyboards: English,Romanian

**Comment by Andrew-Dudov** [comment]
Hello Is your request currently relevant with the new version of the application?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
