### ISSUE TITLE
App crashes from performing certain tasks when Bold text is enabled in system settings

### ISSUE THREAD

**Issue by rasmusthog** [ONLYOFFICE/documents-app-android#260]
### Steps to reproduce

    1) Enable Bold text in system settings
    2) Attempt to do one of the following in ONLYOFFICE Documents (not exhaustive)
    - Open any document
    - Create new document, folder or take a photo
    - Connect to a Nextcloud server

### Expected Behavior
Being able to perform above tasks without the app crashing while Bold text is enabled

### Actual Behavior
The app fully closes when any of the above tasks are attempted. Disabling Bold text in system settings remedies this.

### Software info
Application version 5.5.2
Phone model: Fairphone 4
OS : Android 13 (Calyx OS 4.4.0)

**Comment by Andrew-Dudov** [comment]
Hello @rasmusthog Thank you for your feedback. The root of the problem in Android OS 13. Problems with fonts in the system.
I created a new issue 60409 in our private issue tracker.

**Comment by michael-efremov** [comment]
Fixed since version  #5.6.0
