### ISSUE TITLE
when the OnlyOffice android app is connected to NextCloud, the search icon acts as a filter to the current folder and does not actually search the storage

### ISSUE THREAD

**Issue by vagner-dias** [ONLYOFFICE/documents-app-android#269]
when the android app is connected to NextCloud 25, the search icon acts as a filter to the current folder and does not actually search the storage

Please see the example below

https://user-images.githubusercontent.com/86367839/221429946-ab7a11db-17de-4756-98cc-7ca6faea669a.mp4

**Comment by Andrew-Dudov** [comment]
Hello @vagner-dias Is your request currently relevant with the new version of the application?

**Comment by vagner-dias** [comment]
Hello, @Andrew-Dudov,

I have just checked and, yes, the request is still relevant. The search button is not searching across the whole storage, but only filtering the current folder.

Another "issue" I found is that I have files_lock enabled in my nextcloud instance, so when I open a file using the Android Version of onlyoffice, I expect the file to be locked, but the file is not getting locked. This only happens If I open the file using the web version of OnlyOffice. Should I open another bug report for that ?

Regards,

**Comment by Andrew-Dudov** [comment]
I create ticket 52648 with you issue

**Comment by Andrew-Dudov** [comment]
Can you send a screenshot of the result in the web version and mobile application?

**Comment by vagner-dias** [comment]
Sure.

Below you will find the same search in the NextCloud web Interface (first GIF), NextCloud Android App (Second GIF) and OnlyOffice for Android (Third GIF)
<br><br><br><br>




**NextCloud web Interface**


![2023-11-17_11h28_31](https://github.com/ONLYOFFICE/documents-app-android/assets/86367839/f6bb8f25-a950-4e4e-90ba-0e63306a1ece)

<br><br><br><br>




**NextCloud App**
![Vídeo do WhatsApp de 2023-11-17 à(s) 11 31 23_5c57363f](https://github.com/ONLYOFFICE/documents-app-android/assets/86367839/764e9396-4cb3-45ed-bdce-e8f739087e6c)

<br><br><br><br>


**OnlyOffice for Android** 

![Vídeo do WhatsApp de 2023-11-17 à(s) 11 31 16_029d3f3e](https://github.com/ONLYOFFICE/documents-app-android/assets/86367839/3f5bbf3f-9268-4994-8e91-110a6f340987)

**Comment by Andrew-Dudov** [comment]
@vagner-dias I'm sorry. I'm talking about the files lock issue.
I create ticket 52648 with you issue about search

**Comment by vagner-dias** [comment]
No Problem!

Here are the screenshots:


1st screenshot: Taken from the OnlyOffice Android app while editing the file "teste.xlsx"

2nd screenshot: Taken from the NextCloud Web Interface while editing the file in the android app (file is not locked)

After that, I closed the android app, saved the file.

3rd screenshot: I opened the same file "teste.xlsx" in the OnlyOffice "web version" in one screen, and in the other screen I have the same folder showing the file locked, because is open in the web version.


<br><br><br>
**1st screenshot:** - Editing the file in OnlyOffice for Android
<br>
![Imagem do WhatsApp de 2023-11-17 à(s) 11 57 09_e9b35efb](https://github.com/ONLYOFFICE/documents-app-android/assets/86367839/2d3c3861-277f-49c0-81a8-b8d4b9a525a3)

<br><br><br>
**2nd screenshot:** - File is not locked while editing the file in OnlyOffice for Android
<br>
![2023-11-17_11h53_05](https://github.com/ONLYOFFICE/documents-app-android/assets/86367839/fd22b56f-e043-4a9c-9b06-aba06b8fc855)

<br><br><br>
**3rd screenshot:** - The same file is open in OnlyOffice web version and file is correctly locked in NextCloud
<br>
![2023-11-17_11h56_27](https://github.com/ONLYOFFICE/documents-app-android/assets/86367839/24baf0ec-7685-40ea-ae55-d280d80c9f6f)

**Comment by Andrew-Dudov** [comment]
Hello @vagner-dias Is the bug reproduced only for tables or maybe for a specific file?

**Comment by vagner-dias** [comment]
Hi @Andrew-Dudov, that happens for any file.

**Comment by Andrew-Dudov** [comment]
The application works with Nextcloud using the WEBDAV protocol and overwrites the file, so this behavior is correct

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
