### ISSUE TITLE
Remove trackers

### ISSUE THREAD

**Issue by leslie-kretai** [ONLYOFFICE/documents-app-android#278]
Using a firewall such as rethink it is very easy to see that the app employs a few trackers, obviously this either needs to be removed or disclosed to the user as this is an anti-FLOSS practice.

### IP's and Domains detected by firewall:
142.251.32.67        firebase-settings.crashlytics.com
142.251.41.42        firebaseinstallations.googleapis.com
172.217.13.174      app-measurement.com

**Comment by Andrew-Dudov** [comment]
Hello @leslie-kretai Is your request currently relevant with the new version of the application?

**Comment by leslie-kretai** [comment]
Installed release v8.0.0 to test, previous trackers still coming up and now has a new, additional tracker:

31.13.80.8 graph.facebook.com

**Comment by Andrew-Dudov** [comment]
Hello @leslie-kretai Check out the following issue https://github.com/ONLYOFFICE/documents-app-android/issues/202
