### ISSUE TITLE
Does not work on Fire devices

### ISSUE THREAD

**Issue by NeilJared** [ONLYOFFICE/documents-app-android#279]
It is not available to download from Play Store on a Kindle Fire HD 10 7th gen. Even downloading from unknown sources cannot be installed, in this case due to Security Check not available, as it says, even when allowing installing from unknown sources

**Comment by Andrew-Dudov** [comment]
Hello @NeilJared We do not support the application on your device

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
