### ISSUE TITLE
core-ext and document-android-editors project not found

### ISSUE THREAD

**Issue by yongfengnice** [ONLYOFFICE/documents-app-android#280]
core-ext and document-android-editors project ,please make then open source.can you?otherwise cannot build the project

**Comment by trofim24** [comment]
It's not an open source part.

If you want to use our solution for opening ONLYOFFICE editors based on WebView see [our examples](https://github.com/ONLYOFFICE/editors-webview-android).

Should you have any questions or requests please contact Ascensio System SIA at sales@onlyoffice.com
