### ISSUE TITLE
What's the license of the apks that are attached to the releases?

### ISSUE THREAD

**Issue by rusty-snake** [ONLYOFFICE/documents-app-android#287]
What's the license of the apks that are attached to the releases?
- The repo contains a LICENSE.txt with a APGLv3 license. 
- According to #32 there are other non-(A)GPL repos required to build the apk.

So what's the actual license of the apk? Is it for example allowed to (re-)distribute or disassemble it?

**Comment by Andrew-Dudov** [comment]
Hello @rusty-snake You should contact sales@onlyoffice.com to discuss about license

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
