### ISSUE TITLE
Publish it on fdroid

### ISSUE THREAD

**Issue by marc0x1** [ONLYOFFICE/documents-app-android#297]
F-Droid is an app store and software repository for Android, serving a similar function to the Google Play store. The main repository, hosted by the project, contains only free and open source apps. 

Other important apps are already here, like nextcloud: https://f-droid.org/en/packages/com.nextcloud.client/

To package it, you have to create an issue here with a foss-only flavour:

https://gitlab.com/fdroid/rfp/-/issues

**Comment by michael-efremov** [comment]
Duplicate #2
