### ISSUE TITLE
Deleting Files on Nextcloud Server not possible

### ISSUE THREAD

**Issue by Spheron101** [ONLYOFFICE/documents-app-android#31]
If i delete a file in OnlyOffice Android App (Nextloud Server V20.0.8) the OnlyOffice App creates an error message and the file will not deletet. The deletion of directorys works without problems.

**Comment by Andrew-Dudov** [comment]
Hello,  Is your request currently relevant with the new version of the application?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
