### ISSUE TITLE
First page is smaller than others when opening a document

### ISSUE THREAD

**Issue by ramonls8** [ONLYOFFICE/documents-app-android#312]
If a text document has the Mobile View option turned on, sometimes when you open it, the first page has a smaller size than the others. After you write on it or scroll through the document, it returns to its normal size.

It happens on different devices, on a Xiaomi Mi 10T Lite (running Android 12) and on BlissOS (running Android 11) in Virtual Box.

Here is a video of the issue:

https://github.com/ONLYOFFICE/documents-app-android/assets/96984958/722cc82c-aab3-47e3-89bb-bccf28b2586b

**Comment by andashuai1997** [comment]
Hi，my friend! Would you tell me how to run this project?

**Comment by ramonls8** [comment]
It happens to me almost every time I open any document in Android with Mobile View enabled.

**Comment by Andrew-Dudov** [comment]
Hello @ramonls8 Thank your for your request. I created ticket 59038 with your proposal.

**Comment by Andrew-Dudov** [comment]
bug fixed for version 8.0.0

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
