### ISSUE TITLE
Recent only saved until closure

### ISSUE THREAD

**Issue by regs01** [ONLYOFFICE/documents-app-android#317]
Recent documents won't save. They only appear in the list until the app is closed. Next launch they are not in the list.

Version 7.5.1, but this has been for quite a while.

**Comment by Andrew-Dudov** [comment]
Hello @regs01 Can you describe the steps to reproduce the bug in more detail?

**Comment by regs01** [comment]
> Hello @regs01 Can you describe the steps to reproduce the bug in more detail?

Simply open a file in OnlyOffice, go back to main menu and it's there in the List of Recent. But next time you launch they are not there. Only those created with OnlyOffice are saved in List of Recent permanently.

**Comment by Andrew-Dudov** [comment]
Hello @regs01 is the bug currently relevant on version 8.0?

**Comment by regs01** [comment]
Yes the problem is still there. Recent saving only showing documents created with OnlyOffice, but not opened. And opened only showing in Recent until OnlyOffice is closed.

Aside that in 8.0 i can't open a document from file system from within OnlyOffice. So open file dialog is showing up, but upon selecting a file it just closes back to main screen. I can only open files via in file managers apps.

**Comment by Andrew-Dudov** [comment]
The request to save documents in the "Recent" section is incorrect. The application is working correctly.

**Comment by regs01** [comment]
> The request to save documents in the "Recent" section is incorrect. The application is working correctly.

But that's what list of recent documents for. And it's still not saving documents.

https://github.com/ONLYOFFICE/documents-app-android/assets/10468217/47c76563-e040-4ca2-b338-110552bffc9b
