### ISSUE TITLE
Bulleted list indents bug

### ISSUE THREAD

**Issue by ramonls8** [ONLYOFFICE/documents-app-android#318]
Every time you save a document in the Android app, all bullet list indentations are altered. See the attached video.

https://github.com/ONLYOFFICE/documents-app-android/assets/96984958/ed2fe3ca-4692-4cb5-983b-170cbcc7d896

**Comment by Andrew-Dudov** [comment]
Hello @ramonls8 is the bug currently relevant on version 8.0?
