### ISSUE TITLE
Compile for android

### ISSUE THREAD

**Issue by hi589** [ONLYOFFICE/documents-app-android#32]
**Describe your problem**:

Hello.

I want to compile ONLYOFFICE for android.

This documents-app-android project contains many so files.
[https://github.com/ONLYOFFICE/documents-app-android](url)

What should I compile for those so files?
Is there any guide for android?

Thank you.
Damir

**Comment by michael-efremov** [comment]
Hi. 
Part of the source code are located in private repositories. You can't compile the project without them.

**Comment by hi589** [comment]
Thank you @michael-efremov 

You mean that part of source code are for paid members?
or not ready for distribution?

Can you help me the android compiling?

Thanks.
Damir

**Comment by TheOneWithTheBraid** [comment]
Do you plan to make these parts open source some day? It would be a great step for the whole open source community as ONLYOFFICE is by far the most feature-rich office application we know.

**Comment by meximan** [comment]
Totally agree with @TheOneWithTheBraid

**Comment by itsmeboy0** [comment]
Any update for this?

**Comment by mon-jai** [comment]
@michael-efremov Isn't the source code available in the [public repo](https://github.com/ONLYOFFICE/web-apps/tree/master/apps/documenteditor/mobile)?

**Comment by gmankab** [comment]
> Hi. Part of the source code are located in private repositories. You can't compile the project without them.

please open them

**Comment by Rita-Bubnova** [comment]
Duplicate of https://github.com/ONLYOFFICE/documents-app-android/issues/287.
