### ISSUE TITLE
I cannot copy external text and paste it into a document. 

### ISSUE THREAD

**Issue by joselmm** [ONLYOFFICE/documents-app-android#321]
I would like that the application (document editor) can be filled by external copied text,
sometimes I would like to paste an external copied text (from another app) into a word document.
that is annoying

**Comment by Andrew-Dudov** [comment]
Hello @joselmm Thank your for your request. I created ticket 66428 with your proposal

**Comment by Rita-Bubnova** [comment]
This has been fixed (https://github.com/ONLYOFFICE/core-ext/commit/c9ec9d14e24da35bce95716a1d2beff75b32b97c, https://github.com/ONLYOFFICE/sdkjs-native/commit/b3c06863c38fdb35b7ecff37e592a6a601ab831c).

**Comment by joselmm** [comment]
Error 404 - the pages that You sent don't exist

**Comment by emes81** [comment]
Which release will this be fixed in? It remains a problem for me on 8.0.1.44

**Comment by Andrew-Dudov** [comment]
Hello @emes81 What device do you have? OS version?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.

**Comment by GlassedSilver** [comment]
Please reopen, also I doubt this is a device-specific problem, but of course I am not certain.

My device is a Samsung Galaxy Fold 4.
Android 14
OneUI 6.1.1
Google Play System Patch Level: October 2024

**Comment by Andrew-Dudov** [comment]
Hello @GlassedSilver Is your bug relevant on version 8.2.0?

**Comment by GlassedSilver** [comment]
> Hello @GlassedSilver Is your bug relevant on version 8.2.0?

Oh, will you look at that, 8.2 must have fixed it. Odd that only a few days ago I still had this issue - and normally I regularly update my apps, but good to see it's resolved. It didn't insert my emoji, but ASCII seems to paste fine.

**Comment by Andrew-Dudov** [comment]
@GlassedSilver Did we solve your problem?

**Comment by GlassedSilver** [comment]
Well seems like it's fixed. The emoji not pasting must be a separate unrelated issue I guess? Not sure if it's just me though, maybe you give emojis a quick try and tell me if that's a me problem or whether I may want to create a separate issue for that. In any case this just increased Only Office's viability on Android tenfold. Thank you so much! 🫶

**Comment by Andrew-Dudov** [comment]
Please create another issue
