### ISSUE TITLE
some repository not found

### ISSUE THREAD

**Issue by BinQi** [ONLYOFFICE/documents-app-android#333]
![image](https://github.com/ONLYOFFICE/documents-app-android/assets/4917655/042f1a46-7fdb-4c8e-938a-53d242d498c7)
Help! can't find core-ext and document-android-editors repository. i am so confused

**Comment by charleybin** [comment]
encounted same question.

**Comment by BinQi** [comment]
Thanks for your E-mail. I will reply to it at my earliest convenience.Have a nice day~

**Comment by trofim24** [comment]
Duplicate of https://github.com/ONLYOFFICE/documents-app-android/issues/280

**Comment by BinQi** [comment]
Thanks for your E-mail. I will reply to it at my earliest convenience.Have a nice day~
