### ISSUE TITLE
"Unauthorized request" - Personal ONLYOffice Cloud

### ISSUE THREAD

**Issue by Unbanked0** [ONLYOFFICE/documents-app-android#350]
Hi, experiencing a blocking issue on the Android app :
Unable to connect to my "Personal" account OnlyOffice Cloud

- Credentials login are ok on *.onlyoffice.com
- An error toast appears when trying on Android

- Fresh account (~4h)
- Android 9

Am I doing something wrong ?

![photo_2024-07-18_20-44-42](https://github.com/user-attachments/assets/be27b1ae-46cb-42fe-9f84-18953de38728)

**Comment by Andrew-Dudov** [comment]
Hello @Unbanked0 
Are you sure your credentials are correct?
Can you authenticate in the web version of the portal?

**Comment by Unbanked0** [comment]
Hi,
I updated the app again, it's working !
Only the "back suppr" keyboard key that is not working when editing a sheet
(have to click twice, delete with icon, then fill it again..)

Thanks
Best regards

**Comment by Andrew-Dudov** [comment]
@Unbanked0  I suggest creating a new issue with a description of the bug.

**Comment by Andrew-Dudov** [comment]
Bug for personal account fixed in 8.1.1 version

**Comment by Rita-Bubnova** [comment]
Version 8.1.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
