### ISSUE TITLE
Features of the "On Device" tab are completely broken in 8.2.2 on Pixels with Android 15

### ISSUE THREAD

**Issue by FID02** [ONLYOFFICE/documents-app-android#366]
Any offline document functionality for your app is completely broken in version 8.2.2: when the app is run on a Pixel 6a or 8 device with Android 15, the "On Device" tab displays "Loading files…", but it never completes. Additionally, the message "File with same name already exists" is displayed.

Users are unable to create, view and edit any local files.

Steps to reproduce the issue: 

1. Obtain a Pixel 6a or 8 device and update it to the latest OS version (likely occurs with other device models as well) 
2. Install Onlyoffice from the Play Store
3. Open the app, complete the wizard and grant it the requested storage permission
4. Observe the issue
5. Try to create a new document, and observe that nothing happens

PixelOS build number AP4A.241205.013.A2

**Comment by Andrew-Dudov** [comment]
Hello @FID02 i confirm you problem,  this is the bug 71920

**Comment by Rita-Bubnova** [comment]
@FID02, thanks for checking.
App v8.2.3 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
