### ISSUE TITLE
Support dark theme on Android app.

### ISSUE THREAD

**Issue by xmha97** [ONLYOFFICE/documents-app-android#40]
Hi, please support dark theme on Android app.

**Comment by ayuzhin** [comment]
Under construction. Coming soon.

**Comment by xmha97** [comment]
Thanks.

**Comment by michael-efremov** [comment]
#58 Documents manager dark theme.

**Comment by nav-fess** [comment]
Hello. Dark theme is available in android Onlyoffice Documents v 5,3,0

**Comment by ShockwaveNN** [comment]
Closing this issue since this feature is implemented

**Comment by xmha97** [comment]
Thanks.
