### ISSUE TITLE
FR: Auto fill cells in spreadsheets

### ISSUE THREAD

**Issue by Zahrun** [ONLYOFFICE/documents-app-android#5]
Would love to have the auto fill feature like on the desktop app:
![image](https://user-images.githubusercontent.com/10415894/104791778-3b84b680-579c-11eb-94c4-d7276b71e70b.png)

**Comment by nav-fess** [comment]
Hi, @Zahrun. Created inhansment  40846  in our internal issue tracker.

**Comment by Andrew-Dudov** [comment]
The function is implemented in the latest version

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
