### ISSUE TITLE
Pdf view

### ISSUE THREAD

**Issue by Gottarocket** [ONLYOFFICE/documents-app-android#53]
Currently there is option to view pdf no option to edit or no tools show on viewer to scale or even change view settings Would appreciate such tools

**Comment by nav-fess** [comment]
Hi, @Gottarocket ! We have a third-party pdf viewer. We have plans to replace the pdf viewer. Not soon.

**Comment by Andrew-Dudov** [comment]
Hello @Gottarocket The function you requested was added in version 8.0

**Comment by Rita-Bubnova** [comment]
Version 8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
